info_CLBSample = [
    "Câu lạc bộ bạn tên gì?",
    "Thông tin về Câu lạc bộ của bạn?",
    "Tiêu chí đánh giá trong giai đoạn training là gì, và nếu em chưa giỏi lập trình thì em có thể tham gia câu lạc bộ được không?",
    "CLB có các giải thưởng gì thế?",
    "Quyền lợi và nghĩa vụ của thành viên CLB gồm những gì?",
    "Trong các buổi học của CLB, yêu cầu về học tập và tác phong ra sao?",
    "Nếu như tham gia CLB mình rồi thì có được join bên khác ko?",
    "CLB Lập Trình PTIT có những quyền lợi gì dành cho thành viên ạ?",
    "CLB có bao nhiêu team dự án và khi nào em được tham gia?",
    "Tiêu chí để trở thành “Thành viên tiêu biểu” của CLB là gì?",
    "Quá trình tuyển thành viên và tiêu chí đánh giá gồm những gì?",
    "Khi tham gia CLB, quy định về trang phục và sử dụng trụ sở thế nào?",
    "Tiêu chí đánh giá trong giai đoạn training có gì đặc biệt?",
    "Các team dự án của CLB có hoạt động như thế nào?",
    "Thành viên CLB có thể đảm nhận những vị trí lãnh đạo nào?",
    "Quy trình tuyển chọn và đào tạo thành viên mới của CLB diễn ra như thế nào?",
    "Khi tham gia CLB, thành viên sẽ được hưởng những quyền lợi nào và cần thực hiện những nghĩa vụ gì?",
    "Nội quy về thời gian, trang phục và tác phong trong các buổi học của CLB ra sao?",
    "Các ban và team dự án của CLB hiện gồm những gì và hoạt động ra sao?",
    "Ai đang đảm nhận các vị trí lãnh đạo chính của CLB khóa mới nhất?",
    "Tiêu chí để được xét là “Thành viên tiêu biểu” hàng tháng là gì?",
    "Khi CLB tổ chức liên hoan, thành viên cần tuân thủ những quy định gì?",
    "Văn hóa ứng xử của CLB khuyến khích điều gì trong giao tiếp?",
    "Hoạt động giao lưu giữa CLB và các CLB bạn thường được tổ chức như thế nào?",
    "CLB tổ chức những hoạt động nào để phát triển kỹ năng lập trình cho thành viên?",
    "Quy trình phân công nhiệm vụ trong các team dự án của CLB diễn ra ra sao?",
    "CLB có những quy định gì về bảo quản cơ sở vật chất?",
    "Trong các buổi học, thành viên được khuyến khích hỗ trợ nhau thế nào?",
    "Khi tham gia sự kiện ngoài trường, CthếLB có yêu cầu gì về hình ảnh?",
    "Các vòng tuyển thành viên mới nhằm mục đích gì?",
    "Những hoạt động ngoại khóa nổi bật của CLB là gì?",
    "CLB có những hình thức khen thưởng nào ngoài “Thành viên tiêu biểu”?",
    "Tại sao CLB lại chia thành nhiều team dự án?",
    "Trong buổi họp ban chủ nhiệm, những vấn đề gì thường được bàn đến?",
    "Khi nào CLB yêu cầu thành viên mặc áo đồng phục?",
    "Các tiêu chí đánh giá điểm rèn luyện của thành viên là gì?",
    "Khi làm việc nhóm trong CLB, thành viên cần chú ý điều gì?",
    "Thành viên vi phạm nhiều lần sẽ bị xử lý thế nào?",
    "CLB tổ chức đào tạo những kỹ năng mềm nào?",
    "Các bước chuẩn bị trước một sự kiện lớn của CLB là gì?",
    "CLB hợp tác với những đối tác nào trong các dự án?",
    "Khi tổ chức workshop, CLB yêu cầu thành viên chuẩn bị những gì?",
    "Lệ phí sinh hoạt của CLB là bao nhiêu một kỳ?",
    "Form đăng ký hiện ở đâu, gửi mình link với?",
    "Cho xin tips phỏng vấn (vòng CLB)?",
    "Quy trình tuyển gồm mấy vòng và mỗi vòng đánh giá gì?",
    "Sự kiện workshop tháng này tổ chức ở phòng nào, tại cơ sở nào?",
    "CLB có nhận sinh viên năm nhất không?",
    "CLB PROPTIT khi nào mở đơn tuyển thành viên đợt tới",
    "Có mentor hỗ trợ không?",
    "Nội quy cơ bản là gì?",
    "Có nhận thành viên ngoài trường không?",
    "Kết quả vòng phỏng vấn dự kiến công bố khi nào?"
]


chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Xin chào",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa hay nắng không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?",
    "Chào bạn, hôm nay khỏe không?",
    "Cho mình một câu nói truyền cảm hứng.",
    "Tối nay nên ăn gì giờ?",
    "Bạn có chơi game không?",
    "Bạn ăn cơm chưa?",
    "Bạn thích cà phê hay trà?",
    "Thứ bảy đi chơi ở đâu nhỉ?",
    "Thả một chiếc meme đi.",
    "Bạn thích mèo hay chó?",
    "Cho xin một lời chúc may mắn.",
    "Hãy khen mình một câu đi!",
    "Gợi ý một app quản lý thời gian.",
    "Bạn có thích anime không? (tán gẫu)",
    'Tôi cần giúp đỡ',
    'Tôi là Hà, đến từ Hà Nội và hôm nay tôi thấy buồn',
    'Tôi là Hà, đến từ Hà Nội và hôm nay tôi thấy rất vui',
    'Tôi là Mai, đến từ Đà Nẵng và hôm nay tôi thấy háo hức',
    'Tôi là Quân, đến từ Hải Phòng và hôm nay tôi thấy thất vọng',
    "Hello",
    "Hôm nay tôi lo lắng",
    "Tôi chưa học bài",
    "Ngày mai tôi đi làm",
    "Cuối tuần rảnh nhỉ",
    "Hi"
  
]